# Quick Start:
#
# pip install pre-commit
# pre-commit install && pre-commit install -t pre-push
# pre-commit run --all-files
#
# To Skip Checks:
#
# git commit --no-verify
fail_fast: false

default_language_version:
    python: python3.13.0

repos:
    - repo: https://github.com/psf/black
      rev: 24.10.0
      hooks:
          - id: black
            language_version: python3

    - repo: https://github.com/astral-sh/ruff-pre-commit
      # ruff version.
      rev: v0.7.0
      hooks:
          # Run the linter.
          #
          # When running with --fix, Ruff's lint hook should be placed before Ruff's formatter hook,
          # and before Black, isort, and other formatting tools, as Ruff's fix behavior can output code changes that require reformatting.
          - id: ruff
            args: [--fix]
          # Run the formatter.
          - id: ruff-format
