version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - APP__ENV=prod
      - APP__LOG_LEVEL=INFO
      - APP__SECRET_KEY=change_this_to_a_secure_key
      - APP__ALGORITHM=HS256
      - APP__ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DATABASE__ENGINE=mysql
      - DATABASE__HOST=db
      - DATABASE__PORT=3306
      - DATABASE__USERNAME=ollama_hack
      - DATABASE__PASSWORD=change_this_password
      - DATABASE__DB=ollama_hack
    depends_on:
      - db
    restart: unless-stopped
    expose:
      - 8000
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=ollama_hack
      - MYSQL_USER=ollama_hack
      - MYSQL_PASSWORD=change_this_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    expose:
      - 3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge