version: "3.8"

services:
    ollama-hack:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ollama-hack
        restart: unless-stopped
        ports:
            - "8000:8000"
        volumes:
            - ./data:/app/data
        environment:
            - TZ=Asia/Shanghai
